name: tasky
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11
  flutter_screenutil: ^5.9.3
  country_picker: ^2.0.26

  get_it: ^7.6.7
  dartz: ^0.10.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: any
  retrofit: any
  pretty_dio_logger: any
  logger: any  # for logging purpose
  json_annotation: any
  flutter_secure_storage: ^4.2.1
  dotted_border: ^2.1.0
  cached_network_image: ^3.3.1
  mime: ^1.0.6
  mime_type: ^1.0.1
  image_picker: ^1.0.8
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  retrofit_generator: any

flutter_native_splash:
  color: "#5F33E1"
  image: assets/images/icon.png
  android_12:
    color: "#5F33E1"
    image: assets/images/splash_icon_android_12.png
  #disable for windows
  web : false



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-ExtraBold.ttf
        - asset: assets/fonts/DMSans-ExtraLight.ttf
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #     - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
